variable "prefix" {
  description = "Prefix for resources"
  type        = string
  default     = "dev"
}

variable "name" {
  description = "The topic to create"
  type        = string
}
variable "tags" {
  type        = map(string)
  description = "Tags to apply to the resources generated by this module"
}

locals {
  tags = merge(var.tags, {
    "Source" = "Terraform"
    "Module" = "sns"
  })
}
